site_name: OSINT Village - Book 0.1 DEV

#site_url: https://www.mkdocs.org
site_description: ABase OSINT, inteligencia em outro nivel.
site_author: GreenMind


# Copyright
copyright: Copyright &copy; 2021 GreenMind

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: pt
  features:
    - tabs
    #- instant
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  favicon: assets/favicon.jpeg

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/squidfunk/mkdocs-material
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/squidfunk/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/squidfunk

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home:
    - Home: index.md
  - Infraestrutura:
    - Analise Phishing:
      - A importancia da criação lab: LABS/monitorando-phishings/infraestrutura/a-importancia-criacao-lab.md
      - Requisitos laboratorio: LABS/monitorando-phishings/infraestrutura/requisitos-lab.md
      - Instalando Virtualbox - Linux: LABS/monitorando-phishings/infraestrutura/instalando-virtualbox-linux.md
      - Criando maquina Kali Oficial - Virtualbox: LABS/monitorando-phishings/infraestrutura/criando-lab-kali-oficial-virtualbox.md
      - Criando laboratorio Android - Genymotion: LABS/monitorando-phishings/infraestrutura/instalando-genymotion-linux.md
      - Criando laboratorio Windows - Virtualbox: LABS/monitorando-phishings/infraestrutura/criando-lab-windows-virtualbox.md

  - Laboratorios:
    - Monitoramento de Phishing:
      - 1. Antes de começar:
        - 1.1. Monitorando phishings - Home: LABS/monitorando-phishings/index.md
        - 1.2. Monitorando phishings - Qual o objetivo desse modulo?: LABS/monitorando-phishings/introducao.md
      - 2. Whitehat:
        - 2.1 Monitoramento de dominios: LABS/monitorando-phishings/white/monitorando-dominios.md
        - 2.2 Buscando informações sobre infraestruturas: LABS/monitorando-phishings/white/buscando-informacoes-sobre-infraestruturas.md
        - 2.3 Materiais indexados na internet: LABS/monitorando-phishings/white/materiais-indexados-na-internet.md
        - 2.4 Buscando paginas suspeitas: LABS/monitorando-phishings/white/buscando-paginas-suspeitas.md
        - 2.5 Comunidades: LABS/monitorando-phishings/white/comunidades.md
      - 3. Blackhat:
        - 3.1 Criação de domínios: LABS/monitorando-phishings/black/criacao-dominios.md
        - 3.2 Criando paginas: LABS/monitorando-phishings/black/criando-paginas-suspeitas.md
        - 3.3 Hospedagens: LABS/monitorando-phishings/black/hospedagem.md
        - 3.4 Infraestruturas gratuitas: LABS/monitorando-phishings/black/infraestruturas-gratuitas.md
        - 3.5 Infraestruturas pagas: LABS/monitorando-phishings/infraestruturas-pagas.md
        - 3.6 Configuração de DNS: LABS/monitorando-phishings/configuracao-dns.md
